### PR TITLE
Revert "Tidying"

### PR DESCRIPTION
**Pull request by indigophillips**
Reverts indigogeorgiana/Sprint-2#1

### CODE REVIEW

**Review by sam-by-name — COMMENTED** [review]
line 2 html does not need indentation.
line 3 head also does not need indenting.
everything inside the head only needs to be indented just once

**Review by sam-by-name — COMMENTED** [review]
line 14 div is correct to be indented once, but it needs to be able to see its closing div.

h1 is right to be indented, but h2 should be on the same level as h1.

the header close tag needs to be able to see its opening tag

**Review by sam-by-name — COMMENTED** [review]
with long <p> you should put them over multiple lines and make sure the closing <p> tag and see the opener.
same is true for the <li>.

the div / nav / ul / li / section / footer all need to be on the same level of indentation as their counterparts

**Comment by indigophillips** [comment]
tidying completed

**Pull request closed without merging**
