### PR TITLE
Tidying

### PR DESCRIPTION
**Pull request by indigophillips**
Tidying completed

### CODE REVIEW

**Review by sam-by-name — COMMENTED** [review]
Looking much better :D

A few notes
Line 4 needs to be indented once
Line 13 is to be on the same as the closed head tag.
Line 15 is half indented which is fine (its even preferred by coders i'm told) but if all is not half indented then VS Code does not create the line for at and that makes life much harder for you to see where and if it gets closed.
Line 20 can be on the same as line 19 (so all can come back one also)
line 33 <p> open tag needs to come back to be inline with its closing tag.
and you p tags within div line 31-47 need to be on livel with the close p tag on line 46.
line 49 div needs to be brought back one indent so it can see its closer.
Looking great now up to, the p brackets line 68 - 81, these need to be brought back one indent so they are level with the h3 tag. 
Line 81  p needs to be spread out over multiple lines like the ones above them.
line 85 para needs to be brought back to the same as h3 on line 84.
Lines 102-104 can be brought back just one space so they are the same as line 101.
Line 117 needs to just be the p open tag.

Line 133 is correct to be inline with its opener on line 14, but will of course be brought back to just 1 indent in from nothing :D 
Line 134 needs to see its closer one line 206 as does 
Line 135 with line 205.
Lines 138-167  need to be brought back one indent.
Line 174 -184 can come back one indent and the 
The contents of the <li> tags need to be on there own lines. Line you have done one 140-168.
Lines 188-203 need to be brought back one indent also.
The contents of the <li> tags in lines 189-200 need to be on there own lines. Line you have done one 140-168 and the close li tag on line 202 needs to be on its own line.
Line 205 div needs to see its opener as does line 206 aside tag.
Line 208 body close tag can be brought back to no indent line you have done to its opener.

Good luck!

See it soon :D

**Comment by indigophillips** [comment]
Done -Line 4 needs to be indented once
Done-Line 15 is half indented which is fine (its even preferred by coders i'm told) but if all is not half indented then VS Code does not create the line for at and that makes life much harder for you to see where and if it gets closed.
Done -Line 20 can be on the same as line 19 (so all can come back one also)
Done -line 33 open tag needs to come back to be inline with its closing tag.
Done -and you p tags within div line 31-47 need to be on livel with the close p tag on line 46.- 
Done- line 49 div needs to be brought back one indent so it can see its closer.
Done-Looking great now up to, the p brackets line 68 - 81, these need to be brought back one indent so they are level with the h3 tag.
Done-Line 81 p needs to be spread out over multiple lines like the ones above them.
Done-line 85 para needs to be brought back to the same as h3 on line 84.
Done -Lines 102-104 can be brought back just one space so they are the same as line 101.
Done -Line 117 needs to just be the p open tag.
Done-Line 133 is correct to be inline with its opener on line 14, but will of course be brought back to just 1 indent in from nothing :D
Done- Line 134 needs to see its closer one line 206 as does
Done -Line 135 with line 205.
Done -Lines 138-167 need to be brought back one indent.
Done -Line 174 -184 can come back one indent and the

The contents of the 
Done -tags need to be on there own lines. Line you have done one 140-168.
Done -Lines 188-203 need to be brought back one indent also.

The contents of the 
Done -tags in lines 189-200 need to be on there own lines. Line you have done one 140-168 Done - the close li tag on line 202 needs to be on its own line.
Done - Line 205 div needs to see its opener as does line 206 aside tag.
Done -Line 208 body close tag can be brought back to no indent line you have done to its opener.

Thanks heaps!

**Review by sam-by-name — CHANGES_REQUESTED** [review]
Looking good Indigo,
just a few minor corrections left.
line 13 body tag needs to come back one so it can see its close tag.
Lines 21 - 47 all need to come back one indent.
Line 49 div and all below it need to be brought back one indent. 
Line 51 needs one "space" adding to it so it is level with the p tab below it.
Lines 102 - 130 need to come back one indent.
Line 109+ 116 +128 p tags need to be on there own line.
Line 141 a tag needs pulling back one indent.
Line 143 div needs to be brought forward one indent.
Line 144- 218 need to be brought back one indent Lines 145-216 need to be pushed forwards 1 indent

**Comment by indigophillips** [comment]
All done!

line 13 body tag needs to come back one so it can see its close tag.
Lines 21 - 47 all need to come back one indent.
Line 49 div and all below it need to be brought back one indent.
Line 51 needs one "space" adding to it so it is level with the p tab below it.
Lines 102 - 130 need to come back one indent.
Line 109+ 116 +128 p tags need to be on there own line.
Line 141 a tag needs pulling back one indent.
Line 143 div needs to be brought forward one indent.
Line 144- 218 need to be brought back one indent Lines 145-216 need to be pushed forwards 1 indent

Cheers

**Review by sam-by-name — CHANGES_REQUESTED** [review]
Line 13 body open tag needs to have no indentation, like the close head tag above it.
Line 49 + 50 + 51 need indenting once
Line 66 +67 + 90 + 91 +92 need to be push forward one indent.

Line 99 +100 need indenting 2 time, so they are inline with line 91.
Line 101 h3 tag needs one indent forwards.
Lines 134+135 one indent forwards.
Lines 145-150 need one indent forwards.
Line 148 needs 1 indent forwards.
Line 149 needs 2 indents forwards.
Line 150 +151 needs 3 indents forwards.
Line 152 -183 need 3 indents forwards
Line 184 needs 2 indents forwards
Lines 185-219 needs 3 indents forwards.
Line 187 needs one indent backwards.
Lines 201 -219 needs to be brought back one indent.
and finally line 220 needs to be push forward one indent.
All the best

**Comment by indigophillips** [comment]
All above revised revisions done,

**Review by sam-by-name — COMMENTED** [review]
Line 99 +100 need indenting 2 time, so they are inline with line 91. Still
Lines 134+135 one indent forwards. still
I am not sure what has happened below this point, some cramping up has occurred. Lets sort that now.
145 indent x1
199 +200 indent x 1
all lines 148-219 indent x1
149 indent x1
150 indent x2
151 indent x1
all lines 152-186 indent x1
186 indent x1
187 indent x1
all 196-200 indent x1
188-195 indent x1

not sure what happened from 100 on, but up till then it was perfect :D just a few more now

**Review by sam-by-name — COMMENTED** [review]
line 99 + 100 still needs indenting to the right once.
line 146 needs to come left x1
line 149 needs to go over 3 "spaces"
lines 152 - 182 needs to be indented once to the right.
line 186 needs indenting x 1
lines 188-196 need indenting x1 
and then thats pretty much it

**Comment by indigophillips** [comment]
line 99 + 100 still needs indenting to the right once.
line 146 needs to come left x1
line 149 needs to go over 3 "spaces"
lines 152 - 182 needs to be indented once to the right.
line 186 needs indenting x 1
lines 188-196 need indenting x1
Finished these.

**Review by sam-by-name — APPROVED** [review]

**Pull request merged**
